### ISSUE TITLE
As a developer I want to extend the methods in our repositories, as to extend the functionality of the application

### ISSUE THREAD

**Issue by AVNBuelow** [ITU-BDSA2024-GROUP22/Chirp#79]
Session 07 - 1b

Success Criteria:
- Find Author by name
- Find Author by email
- Create a new Author
- If not implemented already, retrieve cheeps for a certain page.
- If not implemented already, retrieve cheeps for a certain page that are written by a certain Author who is identified by name
- Create a new cheep. Note, that might mean to also create a respective author if she does not exist yet in Chirp!.

**Comment by karokamp** [comment]
All of these methods has been implemented and solved by smaller tickets.
